sudo: false
dist: trusty
language: generic

cache:
  apt: true
  directories:
    - /tmp/tools

matrix:
  include:
    - env: CXX=g++-5 CC=gcc-5
      addons:
        apt:
          packages:
            - g++-5
          sources: &sources
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
    - env: CXX=clang++-3.8 CC=clang-3.8
      addons:
        apt:
          packages:
            - clang-3.8
          sources: *sources

before_install:
  - export PATH="$HOME/bin:$PATH"
  -
  - mkdir ~/bin
  - wget --no-clobber -O /tmp/tools/cmake https://cmake.org/files/v3.4/cmake-3.4.0-rc3-Linux-x86_64.sh || true
  - chmod +x /tmp/tools/*

install:
  - /tmp/tools/cmake --prefix="$HOME" --exclude-subdir

before_script :
  - mkdir build
  - cd build
  - cmake -G"Unix Makefiles" ..

script:
  - make
