sudo: false
language: generic
cache: apt

matrix:
  include:
    - env: CXX=g++-5 CC=gcc-5
      addons:
        apt:
          packages:
            - g++-5
            - cmake
          sources: &sources
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
    - env: CXX=clang++-3.8 CC=clang-3.8
      addons:
        apt:
          packages:
            - clang-3.8
            - cmake
          sources: *sources

before_script :
  - mkdir build
  - cd build
  - cmake -G"Unix Makefiles" ..

script:
  - make
